# Generated by Django 5.1.7 on 2025-03-17 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benutzer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('benutzername', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('kategorienummer', models.AutoField(primary_key=True, serialize=False)),
                ('kategoriebezeichnung', models.CharField(max_length=100)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('kontonummer', models.AutoField(primary_key=True, serialize=False)),
                ('kontobezeichnung', models.CharField(max_length=100)),
                ('kontotyp', models.CharField(max_length=50)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vertrag',
            fields=[
                ('vertragsnummer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ablaufdatum', models.DateField()),
                ('intervall', models.CharField(max_length=50)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategorie')),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.konto')),
            ],
        ),
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('buchungsnummer', models.AutoField(primary_key=True, serialize=False)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buchungsdatum', models.DateField()),
                ('buchungsart', models.CharField(choices=[('Einnahme', 'Einnahme'), ('Ausgabe', 'Ausgabe')], max_length=50)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategorie')),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.konto')),
                ('vertrag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vertrag')),
            ],
        ),
    ]
