# Generated by Django 5.1.7 on 2025-03-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='konto',
            old_name='kontobezeichnung',
            new_name='name',
        ),
    ]
