# Generated by Django 5.1.7 on 2025-03-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_kontobezeichnung_konto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='beschreibung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
