# Generated by Django 5.1.7 on 2025-03-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='monat',
        ),
    ]
