# Generated by Django 5.1.7 on 2025-03-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hauptkategorie_alter_kategorie_benutzer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='hauptkategorie',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='unterkategorien', to='core.hauptkategorie'),
            preserve_default=False,
        ),
    ]
