# Generated by Django 5.1.7 on 2025-03-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_kategorie_hauptkategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertrag',
            name='naechste_buchung',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vertrag',
            name='startdatum',
            field=models.DateField(null=True),
        ),
    ]
